baseURL = 'https://EIG93.github.io'
languageCode = 'en-us'
title = '关于技术和生活的碎碎念'
theme = "paper"

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  #twitter = 'YOUR_TWITTER_ID'               # twitter.com/YOUR_TWITTER_ID
  github = 'EIG93'                 # github.com/YOUR_GITHUB_ID
  #instagram = 'YOUR_INSTAGRAM_ID'           # instagram.com/YOUR_INSTAGRAM_ID
  #linkedin = 'YOUR_LINKEDIN_ID'             # linkedin.com/in/YOUR_LINKEDIN_ID
  #mastodon = 'YOUR_MASTODON_LINK'           # e.g. 'https://mastodon.instance/@xxx'
  rss = true                                # show rss icon

  # home page profile
  avatar = 'http://www.gravatar.com/avatar/?d=identicon&s=32'                 # gravatar email or image url
  name = 'EIG93'
  bio = 'Be humble.'



comments = false                            # disable comments for a specific page
math = true                                 # enable KaTeX math typesetting for a specific page